### ISSUE TITLE
Build -s <signature> flag not implemented

### ISSUE THREAD

**Issue by jonpas** [KoffeinFlummi/armake2#19]
Works with `sign <signature>` but not with `build -s <signature>`. It's just not passed down the execution line.

Also doesn't work with `sign -s <signature>`, but that looks more like a mistake anyways.

**Comment by Krzmbrzl** [comment]
What should `<signature>` be anyways? I think I don't quite understand what it should be used for :thinking:

**Comment by jonpas** [comment]
`bisign` name. For example in ACE3 we add git hash to it.

**Comment by KoffeinFlummi** [comment]
Should work on current master. Fixed the issue with `sign`.
