### ISSUE TITLE
Version number in PBOPREFIX causes runtime issues

### ISSUE THREAD

**Issue by bovine3dom** [KoffeinFlummi/armake2#20]
I'm dealing with an old mod pack which has a few PBOPREFIX files of the form

```
z\LSR\addons\equipment_backpack
version = 65170629⏎
```

This doesn't cause any build-time errors, but at runtime, certain objects can't be found:

Relevant part of RPT:

```
17:51:16 Warning Message: Cannot load texture z\lsr\addons\equipment_backpack\ui\gear_16aa_backpack_daysack_ca.paa.
17:51:16 Warning Message: Cannot load texture z\lsr\addons\equipment_backpack\ui\gear_16aa_backpack_daysack_ca.paa.
17:51:16 Warning Message: Cannot open object z\lsr\addons\equipment_backpack\16aa_backpack_daysack_10.p3d
```

I'm not sure what the version string is from or is for, but could you either ignore it or emit an error at build time?

Thanks.

**Comment by jonpas** [comment]
It is a header extension that seems like is just taken as a long pboprefix with a newline in it.

Either ignore anything after newline or support header extensions from PBOPREFIX file.

**Comment by Krzmbrzl** [comment]
Actually we do support header extensions.
https://github.com/KoffeinFlummi/armake2/blob/5e4aa605929ee092635ce2599519511842ac4e9c/src/pbo.rs#L152
So this appears to be a bug. Do you happen to get this error on windows @bovine3dom?

**Comment by bovine3dom** [comment]
Yup. Linux untested.

**Comment by Krzmbrzl** [comment]
Then I guess this is the same bug as #8 and might be fixed with #9

**Comment by jonpas** [comment]
@bovine3dom tested with #9 AppVeyor build, works correctly and header extension is visible in PBO. :ok_hand:

**Comment by Krzmbrzl** [comment]
Perfect - should we close this issue as a duplicate then?
Hopefully KoffeinFlummi will have the time to merge the PR soon so this problem won't come up anymore ^^

**Comment by bovine3dom** [comment]
Yeah, closing as duplicate of #8. It even works in game.

**Comment by jonpas** [comment]
Merged, he can complain to me now. :D
