### ISSUE TITLE
Allow for remote input

### ISSUE THREAD

**Issue by Krzmbrzl** [KoffeinFlummi/armake2#22]
It would be really cool if the files built by armake didn't have to be local to the machine it is running on.

If one was able to specify a remote git-repo or something like this that should be built or that should be used as an include-path for a build, that'd be awesome.

Example:
`armake build https://github.com/CBATeam/CBA_A3/tree/master/addons/accessory`
or `armake build -i https://github.com/CBATeam/CBA_A3/tree/master/addons/main <myLocalProject>`

**Comment by KoffeinFlummi** [comment]
This is out-of-scope for armake. It would be more appropriate to use some other tool to collect dependencies, cache them locally and invoke armake, or to use some sort of file system level solution to mount remote content.
