### ISSUE TITLE
Define and comment on same line

### ISSUE THREAD

**Issue by jonpas** [KoffeinFlummi/armake2#24]
Following triggers a pre-processor error:
```
#undef PREP // make.py can't redefine already defined macros
```

Work-around:
```
// make.py can't redefine already defined macros
#undef PREP
```

**Comment by Krzmbrzl** [comment]
Did you check that this is actually valid im arm's preprocessor?
If it is, are multiline comments also permitted. 
Also how are do comments influence multiline macros?

**Comment by jonpas** [comment]
It works with Mikero, IIRC it works in Arma directly as well because I use it in missions.

Multiline macros don't support inline comments, period.

**Comment by severgun** [comment]
Same with includes in config.cpp
`#include CfgMySuperFixes.hpp // Best config fixes in the world`

**Comment by Krzmbrzl** [comment]
Okay I just performed a bit of digging and found the following

1. jonpas is right: Comments on the same line as defines is completely valid
2. Single line comments do also break multi-line defines
3. Multi-line comments on the other hand don't

```
#define BLA Something // I am a comment\
is wrong
BLA
```
preprocesses to
```

is wrong
Something 
```

```
#define BLA Something /* I am a comment*/\
is wrong
BLA
```
preprocesses to
```


Something is wrong
```
and
```
#define BLA Something /* I am
a mutline
comment */\
is wrong
BLA
```
preprocesses to
```




Something is wrong
```

**Comment by jonpas** [comment]
Interesting! Was fully sure not even `/* */` comments are supported there.

**Comment by severgun** [comment]
This issue do not allow to build ACE and others who include A3 defines(dikCodes as an example)
