### ISSUE TITLE
Presentation of benchmark results

### ISSUE THREAD

**Issue by Kexanone** [KoffeinFlummi/armake2#4]
You wrote `Time (mean ± σ)`. Maybe I misunderstood your use of symbols, but I would assume that `σ` is the sample standard deviation. The scientific way to present a result, however, would be `Time (mean ± SE)`, where SE is the standard error of the mean (`SE = σ/√n`).

**Comment by commy2** [comment]
In statistics, a normal distributed data set is represented as mean plus/minus standard deviation.

**Comment by Kexanone** [comment]
Yes, the standard deviation gives you the spread of normally distributed data. When you do measurements, you are usually not interested in the spread of the statistical error in the final result, because it depends on your experimental setup, while the value you want to measure does not (excluding systematic errors). What you want to know in this case is the uncertainty for your mean value.

However, I realize that for benchmark results the spread is of interest. A user wants to know how long a run can take (a single measurement), which is better answered when the spread is given too. I just learned something.
