### ISSUE TITLE
Rust 2018 Edition

### ISSUE THREAD

**Issue by BrettMayson** [KoffeinFlummi/armake2#5]
Rust 2018 makes writing rust simpler and removes inconsistencies. It doesn't look like much work would be needed to move armake2 from 2015 to 2018.

More info on Rust 2018 can be found at https://rust-lang-nursery.github.io/edition-guide/rust-2018/index.html

**Comment by KoffeinFlummi** [comment]
Fixed in f1aa2ec220ccf634d36d1eaec0146e29bafd04bf.
