### ISSUE TITLE
Q: Can we download pre-built binaries?

### ISSUE THREAD

**Issue by mwpowellhtx** [KoffeinFlummi/armake2#59]
Or do we have to build for ourselves? I'm just looking for a simple binary download. In my case for Windows 7 x64, but your CI/CD may deliver to other targets, I do not know. Thanks!

**Comment by Neviothr** [comment]
https://ci.appveyor.com/project/KoffeinFlummi/armake2

**Comment by bovine3dom** [comment]
Artifacts are deleted after 6 months so there don't seem to be any, unless I'm missing something :)

**Comment by Neviothr** [comment]
Whoops, didn't notice that. I can send you mine if that helps.

**Comment by mwpowellhtx** [comment]
Pretty sure you can post them to Github as `releases` somehow.

**Comment by Dahlgren** [comment]
Armake "1" has releases with prebuilt binaries on GitHub (https://github.com/KoffeinFlummi/armake/releases) but there hasn't yet been any releases of Armake 2 yet.

Like mentioned before the AppVeyor CI only stores the build artifacts for 6 months.

I've triggered a build based on latest master on AppVeyor, https://ci.appveyor.com/project/Dahlgren/armake2/builds/31808690

**Comment by mwpowellhtx** [comment]
@Dahlgren Well, I do not personally have a build environment. So... Could I ask for an ETA? Also, would you consider a more persistent binary release area? Thank you...

**Comment by bovine3dom** [comment]
@mwpowellhtx that build has completed. This link should get you the exe - https://ci.appveyor.com/api/buildjobs/1vfrdwkip1hi04qi/artifacts/target%2Fx86_64-pc-windows-msvc%2Frelease%2Farmake2.exe - expiring in September 2020.

**Comment by mwpowellhtx** [comment]
Q: 32-bit? or 64-bit?

**Comment by bovine3dom** [comment]
The direct link I gave you is 64 bit. If you need 32 bit it'll be called i686.

**Comment by mwpowellhtx** [comment]
Appreciate it. I see now, thank you.
