### ISSUE TITLE
Include won't work

### ISSUE THREAD

**Issue by Krzmbrzl** [KoffeinFlummi/armake2#8]
When using `armake2 build -i <PathToIncludeFolder> <FolderToBuild> test.pbo` armake fails to resolve the include `#include "\tc\CLib\addons\CLib\macros.hpp"`
So I guess including via absolute path is either not yet implemented or broken.

I am testing this on a windows machine.

It fails with the message
```
←[1;31merror←[0m: Failed to build PBO:
Failed to parse config:
Failed to preprocess config:
Failed to preprocess include "macros.hpp":
File "\tc\CLib\addons\CLib\macros.hpp" included from "\\?\C:\Users\<MyUserName>\Documents\Git\Streamator\addons\Streamator\macros.hpp" not found.```

**Comment by Krzmbrzl** [comment]
This works fine on Linux btw.

**Comment by Krzmbrzl** [comment]
Okay I tracked the error down to the following:
Inside the include-dir there is a `$PBOPREFIX$` with this content:
```
tc\CLib\addons\CLib

```
When I remove that newline from in there it works as expected. I double-checked that the very same newline is present in linux as well. It appears as if there is some problem with the newline on windows specifically.
I am suspecting a classlical `\r\n` vs `\n` problem

**Comment by Krzmbrzl** [comment]
I knew it was that little nasty bug again xD

**Comment by jonpas** [comment]
Hahaha, that quickly went from "WTF" to "fucking Windows".

**Comment by Krzmbrzl** [comment]
Indeed xD
I also found and fixed another bug of that kind in my PR :muscle:
